services:
  database:
    image: mysql:8.0
    container_name: icon_dahomey_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: icon_dahomey
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    

volumes:
  db_data: