parameters:
    app.mailer_from: '%env(MAILER_FROM)%'
    app.stripe_secret_default: ''
    app.sms_default: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\SmsSender:
        arguments:
            $accountSid: '%env(default:app.sms_default:TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(default:app.sms_default:TWILIO_AUTH_TOKEN)%'
            $fromNumber: '%env(default:app.sms_default:TWILIO_FROM)%'

    App\Service\StripeCheckout:
        arguments:
            $secretKey: '%env(default:app.stripe_secret_default:STRIPE_SECRET_KEY)%'
